### ISSUE TITLE
fill height action

### ISSUE THREAD

**Issue by ticruz38** [sw-yx/svelte-actions#16]
Imagine you have an element on the page, and you want him to take the remaining height on the screen
There is no proper answer to this problem with css... But a svelte action would be clean

**Comment by sw-yx** [comment]
i dont understand. why not `height: 100%`

**Comment by ticruz38** [comment]
You want your viewport to not have a scroll bar, sometimes you have a header and some stuffs below, and then you have your element that should fit the rest of the viewport height, height 100% would get your element to go outside the viewport.
This action is quite specific, I'll put it in another repo, never mind.
