### ISSUE TITLE
Shortcut action not working on Crome/Firefox Win 10 

### ISSUE THREAD

**Issue by daevid66** [sw-yx/svelte-actions#24]
Hi, it seems like the key combo you selected in your second example does not work on Windows browsers.

From experimentation I've found that e.altKey and e.shiftKey are both false when also pressing the 2 key (or any other number key).

In contrast, all the following combinations DO work as expected:
Ctrl+2
Alt+2
Shift+Alt+2
Shift+Ctrl+2
Alt+Ctrl+E (or any other non-numerical key I've tried)

This seems very bizarre to me. I'm using a Swedish keyboard but I have not seen any problem like this before. My guess is that  it's a Windows issue.

Maybe it's an ok solution to simply change the used combo in the example, and add a comment on this issue in the action description + code?

Cheers,

/David

**Comment by sw-yx** [comment]
yikes! happy to do that, want to PR?

**Comment by daevid66** [comment]
Hi, the problem is the demo REPL, so I don't think I can do a PR for that. 

I would change the following element:
```
		<td use:shortcut={{shift:true, control: true, code: 'KeyE', callback: () => divCount++}}>
			Will trigger a callback (Cmd/Ctrl + Shift + E)
		</td>
```

**Comment by sw-yx** [comment]
ok i made this https://svelte.dev/repl/aca51811429c4127b1e7ff7eb67a172f?version=3.38.2
