### ISSUE TITLE
Missing ESM module index.mjs

### ISSUE THREAD

**Issue by cbenz** [sw-yx/svelte-actions#25]
The `package.json` file mentions `  "module": "dist/index.mjs"`, but that file is not present in the `svelte-actions` package after installing it from npm, in `node_modules/svelte-actions`. I only find `index.d.ts` and `index.js` in the `dist` directory.

As a result, I get that error when doing `	import { clickOutside } from "svelte-actions"`: `Error: Failed to resolve entry for package "svelte-actions". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "svelte-actions". The package may have incorrect main/module/exports specified in its package.json.` when using SvelteKit, which uses Vite under the hood, which is ESM first.

**Comment by sw-yx** [comment]
sorry for the delay, i'm pretty new to esm build chains. can you check v0.2.1 now? reopen if necessary and help me out if you can
