### ISSUE TITLE
new action proposal: disable on click

### ISSUE THREAD

**Issue by atuttle** [sw-yx/svelte-actions#28]
If there's interest, I'd happily submit a PR to add it.

The classic use case of preventing double-click on form submit. Granted it would probably only ever affect buttons and their lesser siblings, so it has less utility than something like clickOutside:

- `<button>`
- [`<input type="submit" />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit)
- [`<input type="image" />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/image)

... but even with the limited use cases, the expressiveness and readability are pretty fantastic! 🔥 

```html
<script>
  import disableOnClick from 'svelte-actions';
</script>

<button use:disableOnClick>Pay $1,000,000 Now</button>
```

Usually when I roll this type of feature by hand I end up needing to detect when there was an error in form submission and re-enable the form...

```html
<script>
  import disableOnClick from 'svelte-actions';

  let submitInProgress = false;
</script>

<button use:disableOnClick={{disabled: submitInProgress}}>Pay $1,000,000 Now</button>
```

Here's a quick off-the-cuff, completely untested so probably buggy guess implementation:

```js
// disableOnClick.js
export default function disableOnClick(node, params){
  node.disabled = params.disabled === true;

  return {
    update: (newParams) => {
      node.disabled = newParams.disabled === true;
    }
  };
};
```

**Comment by sw-yx** [comment]
prolly a little too simple, but nice suggestion to folks
